# -*- coding: utf-8 -*-
image: ansible/ansible-runner

before_script:
  - pip install --upgrade pip
  - pip install --upgrade ansible ansible-lint
  - ansible --version
  - ansible-lint --version

stages:
  - ansible-lint-syntax-check

ansible-lint:
  stage: ansible-lint-syntax-check
  script:
    - ansible-lint site.yml
    - ansible-playbook --syntax-check site.yml
